version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/nginx/www:/usr/share/nginx
      - $PWD/nginx/log:/var/log/nginx/

  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - $PWD/nginx/www:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/example.env  # change the file to yours
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
